services:
  rag-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - rag_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  rag_network:
    driver: bridge